flags: {}
packages:
- '.'
- circat/
- hermit/
- hermit/examples/HIW13/second/plugin/
- hermit/optimizations/pretty/hermit-pretty/
- hermit-extras/
- kure/
- lambda-ccc/
- netlist/netlist/
- netlist/netlist-to-verilog/
- netlist/netlist-to-vhdl/
- netlist/verilog/
extra-deps:
- applicative-numbers-0.1.3
- marked-pretty-0.1
- ty-0.1.5
- type-unary-0.2.19
resolver: lts-2.22
